/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rustyrazorblade.commmitlog_gui

import com.rustyrazorblade.commmitlog_gui.resources.CommitLogResource
import io.dropwizard.Application
import io.dropwizard.setup.Environment
import java.io.File

class App : Application<MyConfig>() {
    override fun run(configuration: MyConfig, environment: Environment) {
        val path = File("/Users/jhaddad/Dev/cassandra/data/commitlog")
        val resource = CommitLogResource(path)
        environment.jersey().register(resource)
    }
}

fun main(args: Array<String>) {
    println("Starting up")

    App().run(*args)

}
