/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rustyrazorblade.commmitlog_gui

import com.rustyrazorblade.commmitlog_gui.representations.CassandraInterface
import com.rustyrazorblade.commmitlog_gui.resources.CommitLogResource
import io.dropwizard.Application
import io.dropwizard.setup.Environment
import java.io.File

class App : Application<MyConfig>() {
    override fun run(configuration: MyConfig, environment: Environment) {
        // create the right Cassandra
        val path = File(configuration.commitLogs!!)
        val cassandra = CassandraInterface.load()

        val resource = CommitLogResource(cassandra, path)

        environment.jersey().register(resource)
    }
}

fun main(args: Array<String>) {
    println("Starting up")

    App().run(*args)

}
